<LoginScreen>:

    MDBoxLayout:
        orientation: "vertical"
        padding: "40dp"
        spacing: "20dp"

        Widget:

        MDCard:
            orientation: "vertical"
            size_hint: None, None
            size: "420dp", "380dp"
            pos_hint: {"center_x": .5}
            padding: "25dp"
            spacing: "15dp"

            MDLabel:
                text: "Confectionery POS Pro"
                halign: "center"
                font_style: "Headline"

            MDLabel:
                text: "Welcome Back"
                halign: "center"

            MDTextField:
                id: username
                hint_text: "Username"

            MDTextField:
                id: password
                hint_text: "Password"
                password: True

            Widget:

            MDButton:
                style: "filled"
                pos_hint: {"center_x": .5}
                on_release: root.login()

                MDButtonText:
                    text: "LOGIN"

        Widget: