<SplashScreen>:

    MDBoxLayout:
        orientation: "vertical"
        spacing: "20dp"
        padding: "40dp"

        Widget

        MDLabel:
            text: "🍰"
            halign: "center"
            font_style: "Display"

        MDLabel:
            text: "Confectionery POS Pro"
            halign: "center"
            font_style: "Headline"

        MDLabel:
            text: "Version 2.0"
            halign: "center"

        Widget